version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
      - SERVER_HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

